### ISSUE TITLE
EmotionContext version mismatch can break `styled.div(css({...` 

### ISSUE THREAD

**Issue by fcisio** [system-ui/theme-ui#1293]
**Describe the bug**

The theme references in the `import { css } from 'theme-ui'` function don't work on version `v0.5.0-alpha.0`

> It still works in the theme styles, variants, and `sx` prop.

**To Reproduce**
1. Upgrade Theme UI to `v0.5.0-alpha.0`
2. Upgrade Emotion to v11
3. [Rename](https://emotion.sh/docs/emotion-11) the emotion package names in you codebase
4. Use the `css` function from theme-ui in an emotion component

```js
export const StyledHeader = styled.div(
  css({
    // doesn't work
    color: 'primary',
    bg: 'background',
    zIndex: 'nav',
    maxWidth: 'sidebar',
    borderRadius: 'small',

    // works
    px: 4,
  })
)
```

This code outputs

```css
.StyledHeader {
  color: primary;
  background-color: background;
  z-index: nav;
  max-width: sidebar;
  border-radius: small;
  padding-left: 32px;
  padding-right: 32px;
}
```
**Expected behavior**
Should output something like

```css
.StyledHeader {
  color: var(--theme-ui-colors-primary, #000000);
  background-color: var(--theme-ui-colors-background, #ffffff);
  z-index: 10;
  max-width: 350px;
  border-radius: 4px;
  padding-left: 32px;
  padding-right: 32px;
}
```

**Screenshots**
![Shot_0 2](https://user-images.githubusercontent.com/46095852/100023297-b5a74900-2db2-11eb-8392-a4057fa0464f.jpg)
