### ISSUE TITLE
Self hosting fonts w/ Next.js

### ISSUE THREAD

**Issue by johnletey** [system-ui/theme-ui#295]
@jxnblk I have a Next.js site ([source](https://github.com/learn-anything/learn-anything/tree/feature/frontend)), and I'm using Theme UI to style the site

I want to start using the [Inter](https://rsms.me/inter/) font as my default font ... do you know how to import the CSS files and then set the font in my [theme.tsx](https://github.com/learn-anything/learn-anything/blob/feature/frontend/src/theme.tsx) file?

P.S. On the Inter website, they give the following code for importing and using the font:

```css
@import url('https://rsms.me/inter/inter.css');
html { font-family: 'Inter', sans-serif; }
@supports (font-variation-settings: normal) {
  html { font-family: 'Inter var', sans-serif; }
}
```
