### ISSUE TITLE
Styling MDX content doesn't apply on elements with RTL parent

### ISSUE THREAD

**Issue by syncatallah** [system-ui/theme-ui#402]
## Description

Using `theme.styles` object to add styles content in MDX document doesn't apply if I have `dir="rtl"` in the parent!

## Environment
[I am using MDX with create-react-app](https://mdxjs.com/getting-started/create-react-app)

## Steps to reproduce 
- Add styles object to your theme

```css
styles: {
    h1: {
      color: "secondary",
      mt: 4,
      mb: 2
    },
    h3: {
      color: "secondary"
    },
},
```
- Add mdx component
**Note** : Arabic content 

```mdx
  <!-- content.mdx -->
  ### ١٢ اغسطس ٢٠١٩
  # من لا يحب صعود الجبال يعش ابد الدهر بين الحفر
```
- Load mdx component as descriped in MDX [docs](https://mdxjs.com/getting-started/create-react-app), and wrap it by `rtl` div

```jsx
import theme from "./theme";
import { importMDX } from "mdx.macro";
const Content = lazy(() => importMDX("./content.mdx"));

function rtl({ ...props }) {
   return(
      <div dir="rtl">
        <Content />
      </div>
   )
};
```
