### ISSUE TITLE
How to override theme-ui component default variant values?

### ISSUE THREAD

**Issue by geocine** [system-ui/theme-ui#480]
I am currently figuring out a way to override `fontWeight` on the `NavLink` component. This is what the documentation says

> NavLink variants can be defined in the `theme.links` object. By default the NavLink component will use styles defined in `theme.links.nav`.

The default `fontWeight` is `bold` so I created a theme to override this value to `normal` using the configuration below.

```js
{
  ...baseTheme,
  links: {
    nav: {
      fontWeight: 'normal'
    }
  }
}
```

What I got is this from my developer tools
```css
.css-7jwwm1 {
    box-sizing: border-box;
    margin: 0;
    min-width: 0;
    font-weight: normal; /* This is cancelled out */
    font-weight: bold;
    padding: 8px;
    color: inherit;
    text-decoration: none;
    display: inline-block;
}
```

You can see here that the `font-weight` attribute has been repeated twice, which cancels out what I have defined. So how do you do this properly?
