### ISSUE TITLE
CSS custom properties issue

### ISSUE THREAD

**Issue by zce** [system-ui/theme-ui#499]
```css
body {
  --theme-ui-colors-text: var(--theme-ui-colors-text, #495057);
  /* --theme-ui-colors-text => undefined */
}
```

Maybe the right way

```css
body {
  --theme-ui-colors-text: #495057;
  /* --theme-ui-colors-text => #495057 */
}
```

https://codepen.io/zce/pen/rNaaByE

**Comment by zce** [comment]
I will try to submit a PR

**Comment by jxnblk** [comment]
I'm not sure I understand what the issue here is. Could you provide a reproduction?

**Comment by zce** [comment]
I'm sorry, I may not have made it clear.

I mean, there is something wrong with the current color styles.

The color style currently generated is like this

```css
body {
  --theme-ui-colors-text: var(--theme-ui-colors-text, #495057);
  /* --theme-ui-colors-text => undefined */
}
```

In this case `--theme-ui-colors-text` will get `undefined`, then `--theme-ui-colors-text` loses meaning.

At present, all sites that use theme-ui are all in this situation.

![image](https://user-images.githubusercontent.com/6166576/70103774-f88a8100-1676-11ea-9649-a35d5610474a.png)

**Comment by jxnblk** [comment]
I'm still not sure what you're describing. Can you provide a reproduction in Code Sandbox or another repo?

**Comment by zce** [comment]
https://codesandbox.io/s/infallible-hawking-sotbj

https://github.com/zce/custom-properties-issue

**Comment by jxnblk** [comment]
Thanks! First thing I'm noticing is that you *shouldn't* be using the internal custom properties directly, e.g. `color: "var(--theme-ui-colors-primary)"` should be `color: 'primary'`

**Comment by zce** [comment]
I know the right usage, I want to show that I can't get the custom properties defined in body at all.

Because css variables cannot be defined correctly in following way,

```css
body {
  --theme-ui-colors-text: var(--theme-ui-colors-text, #495057);
}
```

The right way is

```css
body {
  --theme-ui-colors-text: #495057;
}
```
