### ISSUE TITLE
Design choice regarding CSS variables in body and themed components

### ISSUE THREAD

**Issue by danvim** [system-ui/theme-ui#569]
This is more of a design choice question for why the `body` tag and other themed components has the following usages of CSS variables.

Currently, the Theme UI site has the following `body` style:

```css
body {
    --theme-ui-colors-text: var(--theme-ui-colors-text,hsl(10,20%,20%));
    --theme-ui-colors-background: var(--theme-ui-colors-background,hsl(10,10%,98%));
    --theme-ui-colors-primary: var(--theme-ui-colors-primary,hsl(10,80%,50%));
    --theme-ui-colors-secondary: var(--theme-ui-colors-secondary,hsl(10,60%,50%));
    --theme-ui-colors-muted: var(--theme-ui-colors-muted,hsl(10,20%,94%));
    --theme-ui-colors-highlight: var(--theme-ui-colors-highlight,hsl(10,40%,90%));
    --theme-ui-colors-gray: var(--theme-ui-colors-gray,hsl(10,20%,50%));
    --theme-ui-colors-accent: var(--theme-ui-colors-accent,hsl(250,60%,30%));
    --theme-ui-colors-darken: var(--theme-ui-colors-darken,rgba(0,0,0,.25));
    color: var(--theme-ui-colors-text,var(--theme-ui-colors-text,
hsl(10,20%,20%)));
background-color: var(--theme-ui-colors-background,var(--theme-ui-colors-background,
    hsl(10,10%,98%)));
}
```

Here is your button on the left (https://theme-ui.com/components/button):

```css
.css-163aye5 {
    box-sizing: border-box;
    margin: 0px 8px 0px 0px;
    min-width: 0px;
    -moz-appearance: none;
    display: inline-block;
    text-align: center;
    line-height: inherit;
    text-decoration: none;
    font-size: inherit;
    padding: 8px 16px;
    border: 0px none;
    border-radius: 4px;
    color: var(--theme-ui-colors-background,
hsl(10,10%,98%));
background-color: var(--theme-ui-colors-primary,
    hsl(10,80%,50%));
    font-weight: 700;
}
```

If we look at the `background-color` property of the button, we can see it either depends on `--theme-ui-colors-primary` or fall back to `hsl(10,80%,50%)`. The nearest definition is at `body`, but body also depends on `--theme-ui-colors-primary`, but it isn't defined on a higher up level.

If we use Inspect and remove the fallback `background-color`, the result will be a transparent button in both Firefox and Chrome:

![image](https://user-images.githubusercontent.com/5255292/72238256-3a182f80-3618-11ea-8e1f-3aedbff9ec08.png)

![image](https://user-images.githubusercontent.com/5255292/72238267-413f3d80-3618-11ea-8e75-36f3499a56b8.png)

My question is, is the CSS variable just for debugging purposes? Since they seem to have no effect on the final render of the components.
