### ISSUE TITLE
Apply `styles.root` on every element or the root `html` element

### ISSUE THREAD

**Issue by kripod** [system-ui/theme-ui#648]
**Is your feature request related to a problem? Please describe.**
Currently, everything passed to `styles.root` gets applied on `body`. When trying to define a global style like below, it generates a `body` and `body h1` selector instead of `*` and `h1`, respectively:

```js
// theme.js
export default {
  styles: {
    root: {
      fontFamily: "'Inter', system-ui, sans-serif",
      h1: { fontSize: '3rem' }
    }
  }
};
```

Results in:

```css
body {
  font-family: 'Inter', system-ui, sans-serif;
}

body h1 {
  fontSize: 3rem;
}
```

**Describe the solution you'd like**
Instead of the code above, the following should be generated:

```css
* {
  font-family: 'Inter', system-ui, sans-serif;
}

h1 {
  fontSize: 3rem;
}
```

When the `body` selector is desired, it should be nested under `styles.root`:

```js
// theme.js
export default {
  styles: {
    root: {
      body: {
        h1: { fontSize: '3rem' } // Results in a `body.h1` selector
      }
    }
  }
};
```

**Describe alternatives you've considered**
As an alternative. an `html` selector could be generated instead of `*`.
