### ISSUE TITLE
(@theme-ui/components): styled system color props don't use values from theme

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#731]
**Describe the bug**

Styled system color props don't use values from the theme.

```jsx
<Image color="text" bg="gray.2" />
```
```css
.css-bla-MyImage {
  color: text;
  background-color: gray.2;
}
```

**To Reproduce**
1. Use color props (handled by Box)
2. Use sx prop on Box
3. Notice the inconsistency

**Expected behavior**

```css
.css-bla-MyImage {
  color: #071d1d;
  background-color: #e6dfdf;
}
```
